#!/bin/bash
cd $(cd $(dirname $0); pwd)
echo -e '\e[1m\e[31m
Storm source is being installed, 
Please wait until the installation is complete
\033[0m'
echo -e '\033[0;33m
If it is the first time to install the source, send the number » {1}
or اذا كانت اول مره تنصيب السورس ارسل رقم » {1}
If you have already installed the source, send the number » {2}
or اذا سبق ونصبت السورس ارسل رقم » {2}
\033[0m'
read Install
case $Install in
1)
echo -e '\033[0;33mOffice installation has begun'
sleep 2
apt update
apt upgrade
sudo apt-get update
sudo apt-get upgrade
sudo  wget https://luarocks.org/releases/luarocks-2.4.3.tar.gz
sudo  tar zxpf luarocks-2.4.3.tar.gz
cd luarocks-2.4.3
./configure; sudo make bootstrap
sudo luarocks install luasocket
sudo luarocks install luasec
sudo luarocks install luautf8
sudo luarocks install redis-lua
sudo  luarocks remove lua-cjson2
sudo  luarocks remove lua-cjson
sudo  apt-get install lua-cjson
sudo luarocks install Lua-cURL
cd ..
sudo apt-get install tmux
sudo apt-get install luarocks
sudo apt-get install screen
sudo apt install zip
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev lua-socket lua-sec lua-expat libevent-dev make unzip git redis-server autoconf g++ libjansson-dev libpython-dev expat libexpat1-dev
sudo apt-get update
sudo apt-get install
sudo apt-get install upstart-sysv
wget http://luarocks.org/releases/luarocks-2.2.2.tar.gz;tar zxpf luarocks-2.2.2.tar.gz;cd luarocks-2.2.2 && ./configure
sudo make bootstrap
sudo luarocks install luasocket
sudo luarocks install luasec
sudo luarocks install lua-term
sudo luarocks install Lua-cURL
sudo service redis-server start
sudo apt-get install libconfig++9v5 -y 
sudo apt-get install libstdc++6 -y
sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y 
sudo apt-get install lua-lgi -y  
sudo apt-get install software-properties-common -y
sudo apt-get install libnotify-dev -y 
sudo apt-get install lua-space -y
sudo apt-get install libreadline-dev libconfig-dev libssl-dev lua5.2 liblua5.2-dev lua-socket lua-sec lua-expat libevent-dev make unzip git redis-server autoconf g++ libjansson-dev libpython-dev expat libexpat1-dev -y
apt install python3.8
apt install python3-pip
python3.8 -m pip install --upgrade pip
python3.8 -m pip install --upgrade setuptools
sudo apt-get update && sudo apt-get upgrade -y
sudo pip3 install -U pip
curl -fssL https://deb.nodesource.com/setup_17.x | sudo -E bash - && sudo apt-get install nodejs -y && npm i -g npm
pip3 install yt-dlp
pip3 install ffmpeg 
apt install ffmpeg
apt install python3-wget
sudo apt install python3-wheel
sudo apt-get update 
sudo apt-get upgrade -y
cd ..
rm -rf luarocks*
unzip tdlua.zip
sudo mv tdlua.so /usr/lib/x86_64-linux-gnu/lua/5.2/tdlua.so
rm -fr tdlua.zip
sudo apt-get update -y
sudo apt-get install -y lua5.2
sudo apt-get install redis-server
pip3.8 install aiofiles
pip3.8 install aiohttp
pip3.8 install asyncio
pip3.8 install asyncstdlib
pip3.8 install dnspython
pip3.8 install ffmpeg-python
pip3.8 install gitpython
pip3.8 install hachoir
pip3.8 install heroku3
pip3.8 install lyricsgenius
pip3.8 install motor
pip3.8 install pillow
pip3.8 install psutil
pip3.8 install redis
pip3.8 install py-tgcalls==0.8.6
pip3.8 install pykeyboard
pip3.8 install pyrogram==1.4.16
pip3.8 install python-dotenv
pip3.8 install requests
pip3.8 install speedtest-cli
pip3.8 install spotipy
pip3.8 install tgcrypto
pip3.8 install wget
pip3.8 install youtube-search
pip3.8 install youtube-search-python
pip3.8 install yt-dlp
pip3.8 install pymongo[srv]
pip3.8 install beautifulsoup4
pip3.8 install pyyaml==5.3.1
sudo lua5.2 Fast.lua
;;
2)
echo -e "\e[1m\e[32mThe bot is running now : جاري تشغيل البوت الان : \e[0m"
sleep 2
unzip tdlua.zip
sudo mv tdlua.so /usr/lib/x86_64-linux-gnu/lua/5.2/tdlua.so
rm -fr tdlua.zip
sudo lua5.2 Fast.lua
;;
esac